"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const courseMockData_1 = require("../controller/courseMockData");
const Payment_1 = require("../controller/Payment");
const VerifyPayment_1 = require("../controller/VerifyPayment");
const router = (0, express_1.Router)();
router.get("/checkuser", courseMockData_1.CourseData);
router.get("/payinit", Payment_1.PayInit);
router.get("/verify/:tx_ref", VerifyPayment_1.VerifyPayment);
exports.default = router;
